# Generated by Django 5.2.1 on 2025-05-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('date_obtention', models.DateField(blank=True, null=True)),
                ('universite', models.CharField(blank=True, max_length=150, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='diplomes/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
